namespace Bugsee
{
    /// <summary>
    /// Package version constants. Regenerated by Tools~/scripts/update-native-sdks.sh.
    /// </summary>
    public static class BugseePackageVersion
    {
        public const string Version = "0.1.0";
        public const string Build = "dev";
        public const string AndroidSdkVersion = "7.3.0";
        public const string IosSdkSource = "https://github.com/bugsee/spm.git";
        public const string IosSdkVersion = "7.0.0-beta5";
        public const string IosSdkCommit = "339f634bfdd1ba0ebcd96ca1d88d790adb64eb52";
    }
}
