namespace Bugsee
{
    /// <summary>
    /// Package version constants. Regenerated by Tools~/scripts/update-native-sdks.sh.
    /// </summary>
    public static class BugseePackageVersion
    {
        public const string Version = "0.1.0";
        public const string AndroidSdkVersion = "7.0.4";
        public const string IosSdkSource = "local-nextgen";
    }
}
