#!/usr/bin/env bash
# Refresh native SDK pins and artifacts for com.bugsee.unity.
#
# - Regenerates Runtime/BugseePackageVersion.cs
# - Updates Editor/BugseeAndroidDependencies.xml Maven coordinates
# - Copies a nextgen Bugsee.xcframework into Native~/ios/Bugsee/ (local SPM)

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
VERSIONS_FILE="${ROOT_DIR}/Tools~/versions.env"

if [[ ! -f "${VERSIONS_FILE}" ]]; then
  echo "Missing ${VERSIONS_FILE}" >&2
  exit 1
fi

# shellcheck disable=SC1090
source "${VERSIONS_FILE}"

RUNTIME_VERSION_CS="${ROOT_DIR}/Runtime/BugseePackageVersion.cs"
ANDROID_DEPS_XML="${ROOT_DIR}/Editor/BugseeAndroidDependencies.xml"
LOCAL_SPM_DIR="${ROOT_DIR}/Native~/ios/Bugsee"
XCFRAMEWORK_DEST="${LOCAL_SPM_DIR}/Bugsee.xcframework"

echo "==> Package ${BUGSEE_PACKAGE_VERSION}"
echo "    Android ${ANDROID_SDK_VERSION}"
echo "    iOS source: ${IOS_SDK_SOURCE} (${IOS_SDK_BRANCH})"

cat > "${RUNTIME_VERSION_CS}" <<EOF
namespace Bugsee
{
    /// <summary>
    /// Package version constants. Regenerated by Tools~/scripts/update-native-sdks.sh.
    /// </summary>
    public static class BugseePackageVersion
    {
        public const string Version = "${BUGSEE_PACKAGE_VERSION}";
        public const string AndroidSdkVersion = "${ANDROID_SDK_VERSION}";
        public const string IosSdkSource = "${IOS_SDK_SOURCE}";
    }
}
EOF
echo "Updated ${RUNTIME_VERSION_CS}"

cat > "${ANDROID_DEPS_XML}" <<EOF
<dependencies>
  <androidPackages>
    <androidPackage spec="${ANDROID_MAVEN_GROUP}:${ANDROID_MAVEN_ARTIFACT}:${ANDROID_SDK_VERSION}" />
    <androidPackage spec="${ANDROID_MAVEN_GROUP}:${ANDROID_FEEDBACK_ARTIFACT}:${ANDROID_SDK_VERSION}" />
  </androidPackages>
</dependencies>
EOF
echo "Updated ${ANDROID_DEPS_XML}"

# --- iOS local SPM xcframework ---
SRC_XCF="${IOS_SDK_REPO_PATH}/${IOS_XCFRAMEWORK_PATH}"
if [[ ! -d "${SRC_XCF}" ]]; then
  echo "WARNING: xcframework not found at ${SRC_XCF}" >&2
  echo "         Build iOS SDK (${IOS_SDK_BRANCH}) and/or set IOS_SDK_REPO_PATH / IOS_XCFRAMEWORK_PATH." >&2
  echo "         Local SPM package will be incomplete until the framework is present." >&2
else
  rm -rf "${XCFRAMEWORK_DEST}"
  mkdir -p "${LOCAL_SPM_DIR}"
  cp -R "${SRC_XCF}" "${XCFRAMEWORK_DEST}"
  echo "Copied ${SRC_XCF} -> ${XCFRAMEWORK_DEST}"
fi

# Keep package.json version in sync when present
PACKAGE_JSON="${ROOT_DIR}/package.json"
if command -v python3 >/dev/null 2>&1 && [[ -f "${PACKAGE_JSON}" ]]; then
  python3 - "${PACKAGE_JSON}" "${BUGSEE_PACKAGE_VERSION}" <<'PY'
import json, sys
path, version = sys.argv[1], sys.argv[2]
with open(path, encoding="utf-8") as f:
    data = json.load(f)
if data.get("version") != version:
    data["version"] = version
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
        f.write("\n")
    print(f"Updated {path} version -> {version}")
else:
    print(f"{path} version already {version}")
PY
fi

echo "Done."
