#!/usr/bin/env bash
# Refresh native SDK pins and artifacts for com.bugsee.unity.
#
# - Regenerates Runtime/BugseePackageVersion.cs
# - Updates Editor/BugseeAndroidDependencies.xml Maven coordinates
# - Optionally copies a prebuilt Bugsee.xcframework into Native~/ios/Bugsee/
#   (set IOS_XCFRAMEWORK_PATH). iOS source of truth is GitHub bugsee-cocoa.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
VERSIONS_FILE="${ROOT_DIR}/Tools~/versions.env"

if [[ ! -f "${VERSIONS_FILE}" ]]; then
  echo "Missing ${VERSIONS_FILE}" >&2
  exit 1
fi

# shellcheck disable=SC1090
source "${VERSIONS_FILE}"

RUNTIME_VERSION_CS="${ROOT_DIR}/Runtime/BugseePackageVersion.cs"
ANDROID_DEPS_XML="${ROOT_DIR}/Editor/BugseeAndroidDependencies.xml"
LOCAL_SPM_DIR="${ROOT_DIR}/Native~/ios/Bugsee"
XCFRAMEWORK_DEST="${LOCAL_SPM_DIR}/Bugsee.xcframework"

echo "==> Package ${BUGSEE_PACKAGE_VERSION}"
echo "    Android ${ANDROID_SDK_VERSION}"
echo "    iOS ${IOS_SDK_REPO} ${IOS_SDK_BRANCH} @ ${IOS_SDK_COMMIT}"

cat > "${RUNTIME_VERSION_CS}" <<EOF
namespace Bugsee
{
    /// <summary>
    /// Package version constants. Regenerated by Tools~/scripts/update-native-sdks.sh.
    /// </summary>
    public static class BugseePackageVersion
    {
        public const string Version = "${BUGSEE_PACKAGE_VERSION}";
        public const string Build = "$(git -C "${ROOT_DIR}" rev-parse --short HEAD 2>/dev/null || echo dev)";
        public const string AndroidSdkVersion = "${ANDROID_SDK_VERSION}";
        public const string IosSdkSource = "${IOS_SDK_REPO}";
        public const string IosSdkBranch = "${IOS_SDK_BRANCH}";
        public const string IosSdkCommit = "${IOS_SDK_COMMIT}";
    }
}
EOF
echo "Updated ${RUNTIME_VERSION_CS}"

cat > "${ANDROID_DEPS_XML}" <<EOF
<dependencies>
  <androidPackages>
    <androidPackage spec="${ANDROID_MAVEN_GROUP}:${ANDROID_MAVEN_ARTIFACT}:${ANDROID_SDK_VERSION}" />
    <androidPackage spec="${ANDROID_MAVEN_GROUP}:${ANDROID_FEEDBACK_ARTIFACT}:${ANDROID_SDK_VERSION}" />
  </androidPackages>
</dependencies>
EOF
echo "Updated ${ANDROID_DEPS_XML}"

# --- iOS pin (GitHub bugsee-cocoa) + optional xcframework copy ---
if command -v git >/dev/null 2>&1; then
  REMOTE_SHA="$(git ls-remote "${IOS_SDK_REPO}" "refs/heads/${IOS_SDK_BRANCH}" 2>/dev/null | awk '{print $1}')"
  if [[ -n "${REMOTE_SHA}" && "${REMOTE_SHA}" != "${IOS_SDK_COMMIT}" ]]; then
    echo "WARNING: ${IOS_SDK_REPO} ${IOS_SDK_BRANCH} is ${REMOTE_SHA}," >&2
    echo "         pin is ${IOS_SDK_COMMIT}. Update IOS_SDK_COMMIT in Tools~/versions.env if intended." >&2
  elif [[ -z "${REMOTE_SHA}" ]]; then
    echo "WARNING: could not resolve ${IOS_SDK_REPO} ${IOS_SDK_BRANCH} (offline or private clone needed)." >&2
  else
    echo "Verified ${IOS_SDK_BRANCH} @ ${IOS_SDK_COMMIT}"
  fi
fi

SRC_XCF="${IOS_XCFRAMEWORK_PATH}"
if [[ -z "${SRC_XCF}" ]]; then
  echo "No IOS_XCFRAMEWORK_PATH set — skipping xcframework copy."
  echo "Build ${IOS_SDK_REPO}@${IOS_SDK_COMMIT} and set IOS_XCFRAMEWORK_PATH to the SPM Bugsee.xcframework."
elif [[ ! -d "${SRC_XCF}" ]]; then
  echo "WARNING: xcframework not found at ${SRC_XCF}" >&2
  echo "         Local SPM package will be incomplete until the framework is present." >&2
else
  rm -rf "${XCFRAMEWORK_DEST}"
  mkdir -p "${LOCAL_SPM_DIR}"
  cp -R "${SRC_XCF}" "${XCFRAMEWORK_DEST}"
  echo "Copied ${SRC_XCF} -> ${XCFRAMEWORK_DEST}"
fi

# Keep package.json version in sync when present
PACKAGE_JSON="${ROOT_DIR}/package.json"
if command -v python3 >/dev/null 2>&1 && [[ -f "${PACKAGE_JSON}" ]]; then
  python3 - "${PACKAGE_JSON}" "${BUGSEE_PACKAGE_VERSION}" <<'PY'
import json, sys
path, version = sys.argv[1], sys.argv[2]
with open(path, encoding="utf-8") as f:
    data = json.load(f)
if data.get("version") != version:
    data["version"] = version
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
        f.write("\n")
    print(f"Updated {path} version -> {version}")
else:
    print(f"{path} version already {version}")
PY
fi

echo "Done."
